global:
  scrape_interval: 5s

scrape_configs:
  - job_name: api-gateway-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: merchant-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:9010"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:9020"]

  - job_name: operations-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:9030"]

  - job_name: vault-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:9040"]
