spring:
  application:
    name: config-service

  cloud:
    config.server.git:
      uri: https://github.com/vishalsaxena111/distributed-monkpay-config
      username: ${CONFIG_GIT_USERNAME:}
      password: ${CONFIG_GIT_PASSWORD:}
      default-label: master

server.port: 8888

